from django.urls import path

from apps.ingestion.views import (
    CatalogAutomationSettingsView,
    CatalogCurationRunBulkDeleteView,
    CatalogCurationRunBulkStopView,
    CatalogCurationRunDetailView,
    CatalogCurationRunListCreateView,
    CatalogCurationRunStopView,
    DuplicateReviewListView,
    DuplicateReviewResolveView,
    ProcessingActivityView,
    ProcessingJobBulkDeleteView,
    ProcessingJobBulkResumeView,
    ProcessingJobBulkStopView,
    ProcessingJobDetailView,
    ProcessingJobListView,
    ProcessingJobLogsView,
    ProcessingJobRecoverView,
    ProcessingJobResumeView,
    ReprocessJobSummaryView,
    ProcessingJobStopView,
    SourceCatalogEntryBulkDeleteView,
    SourceCatalogEntryCreateBooksView,
    SourceCatalogEntryDetailView,
    SourceCatalogEntryListView,
    SourceCatalogRefreshView,
    SourceCatalogRefreshStopView,
    IncompleteCatalogCheckCreateBooksView,
    IncompleteCatalogCheckListView,
    SubmissionBulkDeleteView,
    SubmissionBulkRetryView,
    SubmissionActionLinksView,
    SubmissionBulkStatusView,
    SubmissionConfirmCandidateView,
    SubmissionDetailView,
    SubmissionListCreateView,
    SubmissionRetryView,
)


urlpatterns = [
    path("activity/", ProcessingActivityView.as_view(), name="ingestion-processing-activity"),
    path("submissions/", SubmissionListCreateView.as_view(), name="ingestion-submission-list"),
    path("submissions/status/", SubmissionBulkStatusView.as_view(), name="ingestion-submission-bulk-status"),
    path("submissions/bulk-delete/", SubmissionBulkDeleteView.as_view(), name="ingestion-submission-bulk-delete"),
    path("submissions/bulk-retry/", SubmissionBulkRetryView.as_view(), name="ingestion-submission-bulk-retry"),
    path("submissions/<uuid:pk>/", SubmissionDetailView.as_view(), name="ingestion-submission-detail"),
    path(
        "submissions/<uuid:pk>/confirm-candidate/",
        SubmissionConfirmCandidateView.as_view(),
        name="ingestion-submission-confirm-candidate",
    ),
    path(
        "submissions/<uuid:pk>/action-links/",
        SubmissionActionLinksView.as_view(),
        name="ingestion-submission-action-links",
    ),
    path("submissions/<uuid:pk>/retry/", SubmissionRetryView.as_view(), name="ingestion-submission-retry"),
    path("jobs/", ProcessingJobListView.as_view(), name="ingestion-job-list"),
    path("jobs/reprocess/summary/", ReprocessJobSummaryView.as_view(), name="ingestion-reprocess-summary"),
    path("jobs/recover/", ProcessingJobRecoverView.as_view(), name="ingestion-job-recover"),
    path("jobs/bulk-stop/", ProcessingJobBulkStopView.as_view(), name="ingestion-job-bulk-stop"),
    path("jobs/bulk-resume/", ProcessingJobBulkResumeView.as_view(), name="ingestion-job-bulk-resume"),
    path("jobs/bulk-delete/", ProcessingJobBulkDeleteView.as_view(), name="ingestion-job-bulk-delete"),
    path("jobs/<uuid:pk>/", ProcessingJobDetailView.as_view(), name="ingestion-job-detail"),
    path("jobs/<uuid:pk>/logs/", ProcessingJobLogsView.as_view(), name="ingestion-job-logs"),
    path("jobs/<uuid:pk>/resume/", ProcessingJobResumeView.as_view(), name="ingestion-job-resume"),
    path("jobs/<uuid:pk>/stop/", ProcessingJobStopView.as_view(), name="ingestion-job-stop"),
    path("catalog/entries/", SourceCatalogEntryListView.as_view(), name="ingestion-source-catalog-entry-list"),
    path("catalog/entries/bulk-delete/", SourceCatalogEntryBulkDeleteView.as_view(), name="ingestion-source-catalog-entry-bulk-delete"),
    path("catalog/entries/create-books/", SourceCatalogEntryCreateBooksView.as_view(), name="ingestion-source-catalog-entry-create-books"),
    path("catalog/entries/<uuid:pk>/", SourceCatalogEntryDetailView.as_view(), name="ingestion-source-catalog-entry-detail"),
    path("catalog/refresh/", SourceCatalogRefreshView.as_view(), name="ingestion-source-catalog-refresh"),
    path("catalog/refresh/stop/", SourceCatalogRefreshStopView.as_view(), name="ingestion-source-catalog-refresh-stop"),
    path("catalog/incomplete-check/", IncompleteCatalogCheckListView.as_view(), name="ingestion-incomplete-check-list"),
    path(
        "catalog/incomplete-check/create-books/",
        IncompleteCatalogCheckCreateBooksView.as_view(),
        name="ingestion-incomplete-check-create-books",
    ),
    path("catalog/curation-runs/", CatalogCurationRunListCreateView.as_view(), name="ingestion-catalog-curation-run-list"),
    path("catalog/curation-runs/bulk-stop/", CatalogCurationRunBulkStopView.as_view(), name="ingestion-catalog-curation-run-bulk-stop"),
    path("catalog/curation-runs/bulk-delete/", CatalogCurationRunBulkDeleteView.as_view(), name="ingestion-catalog-curation-run-bulk-delete"),
    path("catalog/curation-runs/<uuid:pk>/", CatalogCurationRunDetailView.as_view(), name="ingestion-catalog-curation-run-detail"),
    path(
        "catalog/curation-runs/<uuid:pk>/stop/",
        CatalogCurationRunStopView.as_view(),
        name="ingestion-catalog-curation-run-stop",
    ),
    path("catalog/automation/", CatalogAutomationSettingsView.as_view(), name="ingestion-catalog-automation-settings"),
    path("duplicate-reviews/", DuplicateReviewListView.as_view(), name="ingestion-duplicate-review-list"),
    path(
        "duplicate-reviews/<uuid:pk>/resolve/",
        DuplicateReviewResolveView.as_view(),
        name="ingestion-duplicate-review-resolve",
    ),
]
