from django.urls import path

from apps.access.views import (
    AccessReferenceDataView,
    BookAssetDownloadView,
    BookSendToKindleView,
    BookmarkDeleteView,
    BookmarkListCreateView,
    HighlightDetailView,
    HighlightListCreateView,
    MyNotesView,
    MyReadingProgressView,
    PermissionGrantDetailView,
    PermissionGrantListCreateView,
    ReaderEpubDownloadView,
    ReaderHighlightTokenDetailView,
    ReaderHighlightTokenListCreateView,
    ReaderHtmlPreviewView,
    ReaderBookmarkTokenDeleteView,
    ReaderBookmarkTokenListCreateView,
    ReaderLaunchView,
    ReaderManifestView,
    ReaderSessionTokenView,
    ReadingSessionView,
)


urlpatterns = [
    path("grants/", PermissionGrantListCreateView.as_view(), name="access-grant-list"),
    path("grants/<uuid:pk>/", PermissionGrantDetailView.as_view(), name="access-grant-detail"),
    path("references/", AccessReferenceDataView.as_view(), name="access-reference-data"),
    path("books/<path:slug>/download/<slug:asset_type>/", BookAssetDownloadView.as_view(), name="access-book-asset-download"),
    path("books/<path:slug>/send-to-kindle/", BookSendToKindleView.as_view(), name="access-book-send-to-kindle"),
    path("books/<path:slug>/reader-launch/", ReaderLaunchView.as_view(), name="access-reader-launch"),
    path("reader/<str:token>/manifest/", ReaderManifestView.as_view(), name="access-reader-manifest"),
    path("reader/<str:token>/epub/<path:asset_path>", ReaderEpubDownloadView.as_view(), name="access-reader-epub-asset"),
    path("reader/<str:token>/epub/", ReaderEpubDownloadView.as_view(), name="access-reader-epub"),
    path("reader/<str:token>/html/", ReaderHtmlPreviewView.as_view(), name="access-reader-html"),
    path("reader/<str:token>/session/", ReaderSessionTokenView.as_view(), name="access-reader-session"),
    path("reader/<str:token>/bookmarks/", ReaderBookmarkTokenListCreateView.as_view(), name="access-reader-bookmark-list"),
    path("reader/<str:token>/bookmarks/<uuid:pk>/", ReaderBookmarkTokenDeleteView.as_view(), name="access-reader-bookmark-delete"),
    path("reader/<str:token>/highlights/", ReaderHighlightTokenListCreateView.as_view(), name="access-reader-highlight-list"),
    path("reader/<str:token>/highlights/<uuid:pk>/", ReaderHighlightTokenDetailView.as_view(), name="access-reader-highlight-detail"),
    path("books/<path:slug>/reading-session/", ReadingSessionView.as_view(), name="access-reading-session"),
    path("books/<path:slug>/bookmarks/", BookmarkListCreateView.as_view(), name="access-bookmark-list"),
    path("books/<path:slug>/highlights/", HighlightListCreateView.as_view(), name="access-highlight-list"),
    path("bookmarks/<uuid:pk>/", BookmarkDeleteView.as_view(), name="access-bookmark-delete"),
    path("highlights/<uuid:pk>/", HighlightDetailView.as_view(), name="access-highlight-detail"),
    path("me/notes/", MyNotesView.as_view(), name="access-my-notes"),
    path("me/reading-progress/", MyReadingProgressView.as_view(), name="access-my-reading-progress"),
]
