# Generated by Django 5.2.12 on 2026-05-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_processing_state_consistency_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcreationrequest',
            name='force_generate',
            field=models.BooleanField(default=False),
        ),
    ]
