# Generated by Django 5.2.12 on 2026-03-21 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCatalogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author_line', models.CharField(blank=True, max_length=255)),
                ('normalized_title', models.CharField(db_index=True, max_length=255)),
                ('normalized_display', models.CharField(db_index=True, max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_type', models.CharField(choices=[('url', 'Direct URL'), ('title', 'Title query'), ('csv', 'CSV import')], max_length=16)),
                ('original_input', models.TextField()),
                ('normalized_input', models.TextField(blank=True)),
                ('resolved_url', models.URLField(blank=True)),
                ('resolution_status', models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved'), ('exact_match', 'Exact match'), ('ambiguous', 'Ambiguous'), ('rejected', 'Rejected'), ('invalid', 'Invalid')], default='unresolved', max_length=24)),
                ('resolution_confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_resolution', 'Pending resolution'), ('queued', 'Queued'), ('processing', 'Processing'), ('needs_review', 'Needs review'), ('ready', 'Ready'), ('failed', 'Failed'), ('duplicate', 'Duplicate candidate')], default='draft', max_length=32)),
                ('review_state', models.CharField(choices=[('pending', 'Pending'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('duplicate_of_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_submissions', to='catalog.book')),
                ('linked_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_submissions', to='catalog.book')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_by', models.CharField(default='exact_source_url', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed'), ('merged', 'Merged')], default='pending', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('raw_evidence', models.JSONField(blank=True, default=dict)),
                ('existing_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_reviews', to='catalog.book')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_reviews', to='ingestion.booksubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('resolution', 'Resolution'), ('ingestion', 'Ingestion'), ('reprocess', 'Reprocess')], default='ingestion', max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('queue_name', models.CharField(blank=True, max_length=100)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to='catalog.book')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='ingestion.booksubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(default='info', max_length=16)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ingestion.processingjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TitleResolutionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.TextField()),
                ('normalized_query', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved'), ('exact_match', 'Exact match'), ('ambiguous', 'Ambiguous'), ('rejected', 'Rejected'), ('invalid', 'Invalid')], default='unresolved', max_length=24)),
                ('confidence', models.FloatField(default=0.0)),
                ('resolved_url', models.URLField(blank=True)),
                ('raw_results', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_attempts', to='ingestion.booksubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('candidate_title', models.CharField(max_length=255)),
                ('candidate_author', models.CharField(blank=True, max_length=255)),
                ('candidate_url', models.URLField()),
                ('confidence', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_selected', models.BooleanField(default=False)),
                ('resolution_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates', to='ingestion.titleresolutionattempt')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
