# Generated by Django 5.2.12 on 2026-03-22 21:34

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_booksubmission_canonical_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogAutomationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.CharField(default='default', max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('daily_run_time', models.TimeField(default=datetime.time(2, 0))),
                ('mode', models.CharField(choices=[('pending', 'Pending only'), ('all', 'All tracked books')], default='pending', max_length=16)),
                ('refresh_max_pages', models.PositiveIntegerField(default=80)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_automation_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['singleton_key'],
            },
        ),
        migrations.CreateModel(
            name='CatalogCurationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=16)),
                ('mode', models.CharField(choices=[('pending', 'Pending only'), ('all', 'All tracked books')], default='pending', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('refresh_catalog', models.BooleanField(default=True)),
                ('refresh_max_pages', models.PositiveIntegerField(default=80)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('queue_name', models.CharField(blank=True, max_length=100)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_curation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
