# Generated by Django 5.2.12 on 2026-03-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_expand_url_field_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksubmission',
            name='origin',
            field=models.CharField(choices=[('user', 'User'), ('curation', 'Source curation'), ('automation', 'Daily automation')], db_index=True, default='user', max_length=16),
        ),
        migrations.AddField(
            model_name='catalogcurationrun',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booksubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_resolution', 'Pending resolution'), ('queued', 'Queued'), ('processing', 'Processing'), ('needs_review', 'Needs review'), ('ready', 'Ready'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('duplicate', 'Duplicate candidate')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='catalogcurationrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16),
        ),
    ]
