# Generated by Django 5.2.12 on 2026-03-21 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedasset',
            name='source_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_assets', to='ingestion.processingjob'),
        ),
        migrations.AddField(
            model_name='metadatareview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_reviews', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='metadatareview',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_metadata_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metadatareview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_metadata_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metadataversion',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_versions', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='metadataversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_versions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_books', to='catalog.series'),
        ),
        migrations.AddField(
            model_name='book',
            name='series_entries',
            field=models.ManyToManyField(related_name='books', through='catalog.BookSeries', to='catalog.series'),
        ),
        migrations.AlterUniqueTogether(
            name='bookcategory',
            unique_together={('book', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='bookcontributor',
            unique_together={('book', 'contributor', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='generatedasset',
            unique_together={('book', 'asset_type')},
        ),
        migrations.AlterUniqueTogether(
            name='bookseries',
            unique_together={('book', 'series')},
        ),
    ]
