# Generated by Django 5.2.12 on 2026-03-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_required',
            field=models.BooleanField(default=False),
        ),
    ]
