# Generated by Django 5.2.12 on 2026-03-21 09:42

import apps.access.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['book__title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('submit:create', 'Submit/create'), ('preview:read_once', 'Preview/read once'), ('read:durable', 'Durable read'), ('download:file', 'Download'), ('metadata:edit', 'Edit metadata'), ('processing:manage', 'Manage processing'), ('access:manage', 'Manage access'), ('admin:full_control', 'Admin/full control')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['user__email', 'scope', 'book__title'],
            },
        ),
        migrations.CreateModel(
            name='PreviewAccessSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=apps.access.models.generate_access_token, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField(default=apps.access.models.default_preview_expiry)),
                ('launch_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_location', models.CharField(blank=True, max_length=255)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('last_opened_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_opened_at'],
            },
        ),
    ]
