# Generated by Django 5.2.12 on 2026-03-21 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('catalog', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissiongrant',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='permissiongrant',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissiongrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='previewaccesssession',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_sessions', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='previewaccesssession',
            name='source_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_sessions', to='ingestion.booksubmission'),
        ),
        migrations.AddField(
            model_name='previewaccesssession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='preview_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_sessions', to='access.previewaccesssession'),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'book', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='readingsession',
            unique_together={('user', 'book')},
        ),
    ]
