# Generated by Django 5.2.12 on 2026-03-22 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_previewaccesssession_user_nullable'),
        ('catalog', '0003_book_normalized_title_category_normalized_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissiongrant',
            options={'ordering': ['user__email', 'scope', 'book__title', 'category__name', 'contributor__name']},
        ),
        migrations.AddField(
            model_name='permissiongrant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='permissiongrant',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='catalog.contributor'),
        ),
    ]
