# Generated by Django 5.2.12 on 2026-05-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_highlight_bookmark_chapter'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='highlight',
            new_name='access_high_user_id_16682d_idx',
            old_name='access_high_user_id_b27ba2_idx',
        ),
        migrations.RenameIndex(
            model_name='highlight',
            new_name='access_high_user_id_19a8c9_idx',
            old_name='access_high_user_id_b1f6d2_idx',
        ),
    ]
