# Generated by Django 5.2.12 on 2026-05-24 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_rename_access_high_user_id_b27ba2_idx_access_high_user_id_16682d_idx_and_more'),
        ('catalog', '0013_curated_book_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='kind',
            field=models.CharField(choices=[('highlight', 'Highlight'), ('quote', 'Quote')], default='highlight', max_length=16),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['user', 'kind'], name='access_high_user_id_85c2ff_idx'),
        ),
    ]
