# Generated by Django 5.2.12 on 2026-06-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_highlight_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongrant',
            name='scope',
            field=models.CharField(choices=[('submit:create', 'Submit/create'), ('preview:read_once', 'Preview/read once'), ('read:durable', 'Durable read'), ('download:file', 'Download'), ('metadata:edit', 'Edit metadata'), ('processing:manage', 'Manage processing'), ('access:manage', 'Manage access'), ('source_records:view', 'View source records'), ('admin:full_control', 'Admin/full control')], max_length=32),
        ),
    ]
