# Generated by Django 5.2.12 on 2026-06-05 20:37

from django.db import migrations, models


def migrate_scopes(apps, schema_editor):
    PermissionGrant = apps.get_model('access', 'PermissionGrant')
    PermissionGrant.objects.filter(scope='preview:read_once').update(scope='preview:html')


def reverse_migrate_scopes(apps, schema_editor):
    PermissionGrant = apps.get_model('access', 'PermissionGrant')
    PermissionGrant.objects.filter(scope='preview:html').update(scope='preview:read_once')


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_alter_permissiongrant_scope'),
    ]

    operations = [
        migrations.RunPython(migrate_scopes, reverse_migrate_scopes),
        migrations.AlterField(
            model_name='permissiongrant',
            name='scope',
            field=models.CharField(choices=[('submit:create', 'Submit/create'), ('preview:html', 'Preview HTML'), ('read:durable', 'Durable read'), ('download:file', 'Download'), ('metadata:edit', 'Edit metadata'), ('processing:manage', 'Manage processing'), ('access:manage', 'Manage access'), ('source_records:view', 'View source records'), ('admin:full_control', 'Admin/full control'), ('send:kindle', 'Send to kindle')], max_length=32),
        ),
    ]
