# Generated by Django 5.2.12 on 2026-07-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0011_bookopeningrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongrant',
            name='scope',
            field=models.CharField(choices=[('submit:create', 'Submit/create'), ('preview:html', 'Preview HTML'), ('read:durable', 'Durable Read'), ('download:file', 'Download Ebook'), ('metadata:edit', 'Edit Metadata'), ('physical_books:view', 'View Physical Books List'), ('processing:manage', 'Manage Processing'), ('access:manage', 'Manage Access'), ('source_records:view', "View Records' Source"), ('admin:full_control', 'Admin/full control'), ('send:kindle', 'Send to Kindle'), ('read:once', 'Read Once')], max_length=32),
        ),
    ]
