# Generated by Django 5.2.12 on 2026-03-22 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksubmission',
            name='canonical_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deduplicated_submissions', to='ingestion.booksubmission'),
        ),
    ]
