# Generated by Django 5.2.12 on 2026-03-22 11:58

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_totp_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, upload_to=apps.accounts.models.profile_image_upload_to),
        ),
    ]
