# Generated by Django 5.2.12 on 2026-03-21 09:42

import apps.catalog.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('needs_review', 'Needs review'), ('ready', 'Ready'), ('published', 'Published'), ('archived', 'Archived'), ('soft_deleted', 'Soft deleted')], default='draft', max_length=32)),
                ('review_state', models.CharField(choices=[('pending', 'Pending'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('source_site', models.CharField(default='ebanglalibrary.com', max_length=100)),
                ('raw_scraped_metadata', models.JSONField(blank=True, default=dict)),
                ('raw_scrape_payload', models.JSONField(blank=True, default=dict)),
                ('main_content_html', models.TextField(blank=True)),
                ('book_info_html', models.TextField(blank=True)),
                ('dedication_html', models.TextField(blank=True)),
                ('toc', models.JSONField(blank=True, default=list)),
                ('cover_source_url', models.URLField(blank=True)),
                ('metadata_last_reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetadataReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetadataVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='scrape', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('raw_value', models.CharField(blank=True, max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_series', to='catalog.book')),
            ],
            options={
                'ordering': ['sort_order', 'series__name'],
            },
        ),
        migrations.CreateModel(
            name='BookSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField()),
                ('normalized_source_url', models.URLField(unique=True)),
                ('source_type', models.CharField(default='ebanglalibrary_book', max_length=50)),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_urls', to='catalog.book')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_value', models.CharField(blank=True, max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_categories', to='catalog.book')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_books', to='catalog.category')),
            ],
            options={
                'ordering': ['category__name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', through='catalog.BookCategory', to='catalog.category'),
        ),
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('author', 'Author'), ('translator', 'Translator'), ('editor', 'Editor'), ('illustrator', 'Illustrator'), ('cover_artist', 'Cover artist'), ('publisher', 'Publisher'), ('other', 'Other')], default='author', max_length=32)),
                ('raw_value', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_contributors', to='catalog.book')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_contributions', to='catalog.contributor')),
            ],
            options={
                'ordering': ['sort_order', 'contributor__name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(related_name='books', through='catalog.BookContributor', to='catalog.contributor'),
        ),
        migrations.CreateModel(
            name='GeneratedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(choices=[('html', 'HTML'), ('epub', 'EPUB'), ('cover', 'Cover')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('file', models.FileField(blank=True, upload_to=apps.catalog.models.generated_asset_upload_to)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('legacy_path', models.CharField(blank=True, max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('is_protected', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_assets', to='catalog.book')),
            ],
            options={
                'ordering': ['asset_type', '-created_at'],
            },
        ),
    ]
