# Generated by Django 5.2.12 on 2026-03-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='normalized_title',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='series',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('source_site', 'normalized_title'), name='uniq_book_source_normalized_title'),
        ),
    ]
