# Generated by Django 5.2.12 on 2026-03-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_book_content_items"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="book",
            name="uniq_book_source_normalized_title",
        ),
    ]
