# Generated by Django 5.2.12 on 2026-05-29 09:37

import apps.catalog.models.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_book_group_and_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedasset',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to=apps.catalog.models.utils.generated_asset_upload_to),
        ),
    ]
