# Generated by Django 5.2.12 on 2026-06-04 16:30

from django.db import migrations


def clean_duplicate_book_sources(apps, schema_editor):
    BookSource = apps.get_model('catalog', 'BookSource')
    from django.db.models import Count
    duplicate_book_ids = (
        BookSource.objects.values('book')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
        .values_list('book', flat=True)
    )
    for book_id in duplicate_book_ids:
        sources = list(
            BookSource.objects.filter(book_id=book_id).order_by('-is_primary', '-created_at')
        )
        if len(sources) > 1:
            for source in sources[1:]:
                source.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_add_performance_indexes'),
    ]

    operations = [
        migrations.RunPython(clean_duplicate_book_sources, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='booksource',
            unique_together={('book',)},
        ),
    ]
