# Generated by Django 4.2.30 on 2026-06-30 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_remove_book_last_kindle_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='manual_language',
            field=models.CharField(blank=True, default='bn', max_length=16),
        ),
        migrations.AlterField(
            model_name='book',
            name='source_site',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booksource',
            name='source_type',
            field=models.CharField(default='source_site_book', max_length=50),
        ),
        migrations.AlterField(
            model_name='userbookkindlesend',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
